# Generated by Django 4.2.11 on 2026-05-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('PASAPORTE', 'Pasaporte'), ('CARNET_EXTRANJERIA', 'Carnet de extranjería')], default='DNI', max_length=30)),
                ('num_doc', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'Huésped',
                'verbose_name_plural': 'Huéspedes',
                'db_table': 'huespedes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
