# Generated by Django 4.2.11 on 2026-07-04 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('huespedes', '0003_huesped_modelobase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='huesped',
            options={'ordering': ['apellidos', 'nombres'], 'verbose_name': 'Huesped', 'verbose_name_plural': 'Huespedes'},
        ),
        migrations.AlterField(
            model_name='huesped',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
