# Generated by Django 4.2.11 on 2026-07-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0004_alter_huesped_options_alter_huesped_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='tipo_doc',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('PAS', 'Pasaporte'), ('CE', 'Carné de Extranjería')], default='DNI', max_length=30),
        ),
    ]
