# Generated by Django 4.2.11 on 2026-05-07 23:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hoteles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amenidades', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Tipo de Habitación',
                'verbose_name_plural': 'Tipos de Habitación',
                'db_table': 'tipos_habitacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='habitaciones.tipohabitacion')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'db_table': 'tarifas',
                'ordering': ['tipo_habitacion', 'fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('piso', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('LIMPIEZA', 'Limpieza'), ('MANTENIMIENTO', 'Mantenimiento')], default='DISPONIBLE', max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='hoteles.hotel')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='habitaciones.tipohabitacion')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'db_table': 'habitaciones',
                'ordering': ['hotel', 'piso', 'numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='habitacion',
            constraint=models.UniqueConstraint(fields=('hotel', 'numero'), name='unique_habitacion_por_hotel'),
        ),
    ]
