# Generated by Django 4.2.11 on 2026-05-07 23:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estancias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('PENDIENTE', 'Pendiente de pago'), ('PAGADO', 'Pagado'), ('CERRADO', 'Cerrado'), ('ANULADO', 'Anulado')], default='ABIERTO', max_length=20)),
                ('estancia', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='folio', to='estancias.estancia')),
            ],
            options={
                'verbose_name': 'Folio',
                'verbose_name_plural': 'Folios',
                'db_table': 'folios',
                'ordering': ['-id'],
            },
        ),
    ]
