# Generated by Django 4.2.11 on 2026-07-18 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuentas', '0003_usuarioempleado_modelobase'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles_efectivos', models.CharField(blank=True, max_length=100)),
                ('motivo', models.CharField(choices=[('idle_timeout', 'Inactividad'), ('absolute_timeout', 'Límite absoluto'), ('legacy_session', 'Sesión sin política vigente')], max_length=20)),
                ('ruta', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_sesion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de sesión',
                'verbose_name_plural': 'Auditorías de sesión',
                'db_table': 'auditorias_sesion',
                'ordering': ('-creado_en',),
                'indexes': [models.Index(fields=['usuario', 'creado_en'], name='auditorias__usuario_7b7a76_idx'), models.Index(fields=['motivo', 'creado_en'], name='auditorias__motivo_39e78c_idx')],
            },
        ),
    ]
