# Generated by Django 6.0.5 on 2026-05-16 22:16

from django.db import migrations, models


def normalizar_cargos(apps, schema_editor):
    Empleado = apps.get_model('empleados', 'Empleado')
    equivalencias = {
        'administrador': 'ADMINISTRADOR',
        'admin': 'ADMINISTRADOR',
        'recepcionista': 'RECEPCIONISTA',
        'recepcion': 'RECEPCIONISTA',
        'recepción': 'RECEPCIONISTA',
        'housekeeping': 'HOUSEKEEPING',
        'limpieza': 'HOUSEKEEPING',
        'supervisor': 'SUPERVISOR',
        'mantenimiento': 'MANTENIMIENTO',
        'contabilidad': 'CONTABILIDAD',
        'contador': 'CONTABILIDAD',
    }

    for empleado in Empleado.objects.all():
        cargo_actual = (empleado.cargo or '').strip()
        cargo_normalizado = equivalencias.get(cargo_actual.lower(), cargo_actual.upper())
        if cargo_normalizado not in {
            'ADMINISTRADOR',
            'RECEPCIONISTA',
            'HOUSEKEEPING',
            'SUPERVISOR',
            'MANTENIMIENTO',
            'CONTABILIDAD',
            'OTRO',
        }:
            cargo_normalizado = 'OTRO'

        empleado.cargo = cargo_normalizado
        empleado.save(update_fields=['cargo'])


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normalizar_cargos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('RECEPCIONISTA', 'Recepcionista'), ('HOUSEKEEPING', 'Housekeeping'), ('SUPERVISOR', 'Supervisor'), ('MANTENIMIENTO', 'Mantenimiento'), ('CONTABILIDAD', 'Contabilidad'), ('OTRO', 'Otro')], default='RECEPCIONISTA', max_length=30),
        ),
    ]
