# Generated by Django 4.2.11 on 2026-05-07 23:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_checkin', models.DateTimeField()),
                ('fecha_checkout', models.DateTimeField(blank=True, null=True)),
                ('precio_final', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estancias', to='habitaciones.habitacion')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estancia', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Estancia',
                'verbose_name_plural': 'Estancias',
                'db_table': 'estancias',
                'ordering': ['-fecha_checkin'],
            },
        ),
        migrations.CreateModel(
            name='CargoEstancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('HABITACION', 'Habitación'), ('RESTAURANTE', 'Restaurante'), ('LAVANDERIA', 'Lavandería'), ('MINIBAR', 'Minibar'), ('PENALIDAD', 'Penalidad'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('estancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='estancias.estancia')),
            ],
            options={
                'verbose_name': 'Cargo de Estancia',
                'verbose_name_plural': 'Cargos de Estancia',
                'db_table': 'cargos_estancia',
                'ordering': ['-fecha'],
            },
        ),
    ]
