# Generated by Django 4.2.11 on 2026-05-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('direccion', models.TextField()),
                ('estrellas', models.PositiveSmallIntegerField()),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'db_table': 'hoteles',
                'ordering': ['nombre'],
            },
        ),
    ]
