# Generated by Django 4.2.11 on 2026-05-07 23:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
        ('hoteles', '0001_initial'),
        ('huespedes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('num_adultos', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('CHECKIN', 'Check-in realizado'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('origen', models.CharField(choices=[('WEB', 'Web'), ('TELEFONO', 'Teléfono'), ('RECEPCION', 'Recepción'), ('AGENCIA', 'Agencia'), ('OTRO', 'Otro')], default='RECEPCION', max_length=20)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='habitaciones.habitacion')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hoteles.hotel')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='huespedes.huesped')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
                'ordering': ['-fecha_entrada'],
            },
        ),
    ]
