# Generated by Django 4.2.11 on 2026-07-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='origen',
            field=models.CharField(choices=[('TELEFONO', 'Teléfono'), ('RECEPCION', 'Recepción')], default='RECEPCION', max_length=20),
        ),
    ]
